api_key = "2ywFMDc8MAMvmkuoVyrEWbPET2_-0A4tn9JxmYHJ"
google_api_key = "AIzaSyBFEC7f60pR9dx1-fCLSVDUEkb9z9GuSHo"

title = "Discover and unlock the power of event intelligence for your locations:"
suggested_radius_industry = "accommodation"
